main.plugins.niu-bt-tether.enabled = true # if you want to use this, set ui.display.video.address to 0.0.0.0
main.plugins.niu-bt-tether.devices.android-phone.enabled = true
main.plugins.niu-bt-tether.devices.android-phone.search_order = 1
main.plugins.niu-bt-tether.devices.android-phone.mac = "C0:BD:C8:31:78:EE" # mac of your bluetooth device
main.plugins.niu-bt-tether.devices.android-phone.ip = "192.168.44.45" # ip from which your pwnagotchi should be reachable
main.plugins.niu-bt-tether.devices.android-phone.netmask = 24
main.plugins.niu-bt-tether.devices.android-phone.interval = 1 # check every x minutes for device
main.plugins.niu-bt-tether.devices.android-phone.scantime = 10
main.plugins.niu-bt-tether.devices.android-phone.max_tries = 10
main.plugins.niu-bt-tether.devices.android-phone.share_internet = true
main.plugins.niu-bt-tether.devices.android-phone.priority = 1

main.plugins.niu-bt-tether.devices.ios-phone.enabled = false
main.plugins.niu-bt-tether.devices.ios-phone.search_order = 2
main.plugins.niu-bt-tether.devices.ios-phone.mac = ""
main.plugins.niu-bt-tether.devices.ios-phone.ip = "172.20.10.6"
main.plugins.niu-bt-tether.devices.ios-phone.netmask = 24
main.plugins.niu-bt-tether.devices.ios-phone.interval = 5
main.plugins.niu-bt-tether.devices.ios-phone.scantime = 20
main.plugins.niu-bt-tether.devices.ios-phone.max_tries = 0
main.plugins.niu-bt-tether.devices.ios-phone.share_internet = false
main.plugins.niu-bt-tether.devices.ios-phone.priority = 999